# language: node_js
# node_js:
#   - "4.0"
# script:
#   - echo "deploying"
# install:
#   - npm install -g firebase-tools
# after_success:
#   - firebase deploy --token $FIREBASE_TOKEN

language: node_js
node_js:
  - "11.0"
before_script:
  - npm install -g firebase-tools
script:
  - cd ./client
  - npm install
  - unset CI
  - npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
